### ISSUE TITLE
Add Goetz_RecoveryGenes dataset?

### ISSUE THREAD

**Issue by mslw** [sfb1451/projects-C01#2]
I have seen this dataset in GIN: https://gin.g-node.org/Aswendt_Lab/2023_Goetz_RecoveryGenes. It credits SFB 1451 funding and seems like a candidate for inclusion in the C01 superdataset. However, it has not been included in recent changes to the subdatsets done in the master branch.

I had included that one in "my" `sfb-retreat-2023` branch (b1e4f30a0474a2216f8ce20bfdc7a8e365cbe6f2) that was used to generate catalog preview until now.

I'll need clarification from @maswendt or @arefks on whether the dataset should be included.

**Comment by arefks** [comment]
It should be included. You are correct.
