### ISSUE TITLE
What to do with non-DataLad submodules?

### ISSUE THREAD

**Issue by mslw** [sfb1451/projects-C01#3]
There are currently two subdatasets (submodules) which aren't DataLad datasets, meaning that they have no dataset ID. This is not a problem for most if not all regular DataLad operations (subdatasets *are* submodules). However, this is a problem for DataLad-catalog which needs an ID for each dataset it displays.

The affected datasets are:
- AIDAqc
- 2023_Stokowska_Periinfarct

@arefks @maswendt please let me know which way to address this would *you* prefer:
1. Use `datalad create [--no-annex] --force`, effectively adding the `.datalad/config` file with the identifier; this would not change anything in how the repositories function
2. Make no changes to the repositories and have us figure how to "mint" an identifier for catalog display purposes.

Related issue in SFB catalog repo: https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/30

<hr>

As a side note: I have seen that the https://gin.g-node.org/Aswendt_Lab/2023_Stokowska_Periinfarct repo has an issue where "synced" branches have been published to GIN, and some commits are mismatched with their counterparts. I do not fully understand what state it should be in. This caused problems when I was trying to work with the repo to extract metadata. I had previously created a [fork](https://gin.g-node.org/msz/2023_Stokowska_Periinfarct) where I resolved the mismatch as best as I could and added the dataset ID afterwards. However, it seems to me that you would prefer to link to your original repo.

**Comment by arefks** [comment]
I did ` datalad create --no-annex --force` to my AIDAqc repo which should resolve the problem for now.

Regarding the Stokowska dataset, I was once struggling with that repo too. Your forked repo seems to be the same only four commits ahead in which you have merged the sync into the master branch, but still looks not clean. As it was already published in GIN with a DOI, we didn't want to change it. I would suggest now merging your fork changes to our repo, couldn't find a way to do it directly on GIN though. How do you propose doing this? (Just FYI: we have set the Synced/Master branch to the default branch) @mslw

**Comment by mslw** [comment]
> I did  datalad create --no-annex --force to my AIDAqc repo which should resolve the problem for now.

Thanks! I think that'll be useful, if only as an additional resource identifier.

> Regarding the Stokowska dataset, I was once struggling with that repo too. Your forked repo seems to be the same only four commits ahead in which you have merged the sync into the master branch, but still looks not clean.

This is a correct assessment of what I did. It would be interesting to figure out what makes it "not clean", but that is a separate discussion, probably best to be had on GIN.

> As it was already published in GIN with a DOI, we didn't want to change it.

I think the DOI should not be an obstacle for making tweaks, especially if they are fixing some problems - if you go to GIN's landing page for https://doi.org/10.12751/g-node.699mgv, it gives you two buttons: "Browse repository" (*Browse the live dataset's contents on GIN. The repository may contain updates.*) that goes to your dataset's landing page, and "Browse archive" (*Browse the archived dataset's contents on GIN. This is a snapshot of the published version.*) that goes to a fork created under "G-Node DOI" at the moment of DOI assignment.

> I would suggest now merging your fork changes to our repo, couldn't find a way to do it directly on GIN though. How do you propose doing this? (Just FYI: we have set the Synced/Master branch to the default branch)

Thanks, I think that's the best way forward. I'll open a PR in GIN (I think to do it on GIN, the request must come from me). Maybe we can wait a bit with merging and have a second look at the state it's in. edit: [here's the PR](https://gin.g-node.org/Aswendt_Lab/2023_Stokowska_Periinfarct/pulls/1).

**Comment by mslw** [comment]
We now have DataLad dataset ID for both datasets :ok_hand: -- thanks for help!
