### ISSUE TITLE
Unable to get Example_Dataset_Kalantari_Paper subdataset

### ISSUE THREAD

**Issue by mslw** [sfb1451/projects-C01#5]
When trying to install the subdataset, I get the following error:

```
❱ datalad get --no-data Example_Dataset_Kalantari_Paper 
install(error): /tmp/projects-C01/Example_Dataset_Kalantari_Paper (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- git@gin.g-node.org:/Aswendt_Lab/Example_Dataset_Kalantari_Paper.git
  CommandError: 'git -c diff.ignoreSubmodules=none -c core.quotepath=false clone --progress git@gin.g-node.org:/Aswendt_Lab/Example_Dataset_Kalantari_Paper.git /tmp/projects-C01/Example_Dataset_Kalantari_Paper' failed with exitcode 128 [err: 'Cloning into '/tmp/projects-C01/Example_Dataset_Kalantari_Paper'...
GIN: Repository does not exist or you do not have access
(...)
```

In `.gitmodules`, the following URL is recorded - but I can't find a repo with that name on GIN.:
```
url = git@gin.g-node.org:/Aswendt_Lab/Example_Dataset_Kalantari_Paper.git
```

I am fairly sure that the repo was moved to [Aswendt_Lab/2023_Kalantari_DataladExampleDataset](https://gin.g-node.org/Aswendt_Lab/2023_Kalantari_DataladExampleDataset) instead, and I will update the URLs accordingly unless stoped by @arefks.

**Comment by arefks** [comment]
You are correct. The name was changed to create more homogeneity. Thanks for correcting it.

**Comment by mslw** [comment]
Ping psychoinformatics-de/sfb1451-projects-catalog#35 and psychoinformatics-de/sfb1451-projects-catalog#49
